name: .NET 8 CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: [win-x64, win-x86, win-arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore -p:DebugType=none

    - name: Run tests for Core
      run: dotnet test ContactKeeper.Core.Tests/ContactKeeper.Core.Tests.csproj --no-build --verbosity normal

    - name: Run tests for Infrastructure
      run: dotnet test ContactKeeper.Infrastructure.Tests/ContactKeeper.Infrastructure.Tests.csproj --no-build --verbosity normal

    - name: Run tests for UI
      run: dotnet test ContactKeeper.UI.Tests/ContactKeeper.UI.Tests.csproj --no-build --verbosity normal

    - name: Publish artifact
      if: always()
      run: dotnet publish ContactKeeper.UI/ContactKeeper.UI.csproj -c Release -o ${{github.workspace}}/publish/${{ matrix.architecture }} --self-contained -r ${{ matrix.architecture }} -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ContactKeeper-${{ matrix.architecture }}
        path: ${{github.workspace}}/publish/${{ matrix.architecture }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: ./release-notes.md
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/publish/ContactKeeper-${{ matrix.architecture }}-${{ github.ref }}.zip
        asset_name: ContactKeeper-${{ matrix.architecture }}-${{ github.ref }}.zip
        asset_content_type: application/zip
